### ISSUE TITLE
Running luminoth a third time from the app is resulting in the below error when it tries to use the checkpoint

### ISSUE THREAD

**Issue by pranathivemuri** [czbiohub/napari-bb-annotations#12]
```      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
      type: DT_FLOAT
    }
  }
}

        op = <tf.Operation 'save/RestoreV2' type=RestoreV2>
        message = 'Key fasterrcnn_1/rcnn/fc_bbox/b not found in checkpoint\n\t [[node save/RestoreV2 (defined at /Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/luminoth/utils/predicting.py:61) ]]'
   1349 

NotFoundError: Key fasterrcnn_1/rcnn/fc_bbox/b not found in checkpoint
	 [[node save/RestoreV2 (defined at /Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/luminoth/utils/predicting.py:61) ]]

Caused by op 'save/RestoreV2', defined at:
  File "./napari_bb_annotations/launcher/bb_annotations.py", line 17, in <module>
    main()
  File "./napari_bb_annotations/launcher/bb_annotations.py", line 13, in main
    launch_viewer()
  File "./napari_bb_annotations/launcher/bb_annotations.py", line 9, in launch_viewer
    connect_to_viewer(viewer)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/napari/_qt/qt_event_loop.py", line 253, in gui_qt
    run(force=force, gui_exceptions=gui_exceptions, _func_name='gui_qt')
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/napari/_qt/qt_event_loop.py", line 347, in run
    app.exec_()
  File "/Users/pranathi.vemuri/napari-bb-annotations/napari_bb_annotations/gui.py", line 31, in <lambda>
    run_lumi_btn.clicked.connect(lambda: run_lumi_on_image(viewer))
  File "/Users/pranathi.vemuri/napari-bb-annotations/napari_bb_annotations/_key_bindings.py", line 634, in run_lumi_on_image
    classes_json, pixel_distance, new_labels)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/luminoth/predict.py", line 437, in predict_function
    network = PredictorNetwork(config)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/luminoth/utils/predicting.py", line 61, in __init__
    saver = tf.train.Saver(sharded=True, allow_empty=True)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 507, in _build_internal
    restore_sequentially, reshape)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 385, in _AddShardedRestoreOps
    name="restore_shard"))
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Key fasterrcnn_1/rcnn/fc_bbox/b not found in checkpoint
	 [[node save/RestoreV2 (defined at /Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/luminoth/utils/predicting.py:61) ]]


During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
~/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py in restore(self=<tensorflow.python.training.saver.Saver object>, sess=<tensorflow.python.client.session.Session object>, save_path='/Users/pranathi.vemuri/.luminoth/checkpoints/1a0f3002f674/model.ckpt-837929')
   1285       try:
-> 1286         names_to_keys = object_graph_key_mapping(save_path)
        names_to_keys = undefined
        global object_graph_key_mapping = <function object_graph_key_mapping at 0x7fde8bca1b70>
        save_path = '/Users/pranathi.vemuri/.luminoth/checkpoints/1a0f3002f674/model.ckpt-837929'
   1287       except errors.NotFoundError:

~/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py in object_graph_key_mapping(checkpoint_path='/Users/pranathi.vemuri/.luminoth/checkpoints/1a0f3002f674/model.ckpt-837929')
   1590   object_graph_string = reader.get_tensor(
-> 1591       checkpointable.OBJECT_GRAPH_PROTO_KEY)
        global checkpointable.OBJECT_GRAPH_PROTO_KEY = '_CHECKPOINTABLE_OBJECT_GRAPH'
   1592   object_graph_proto = (

~/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in get_tensor(self=<tensorflow.python.pywrap_tensorflow_internal.Ch...ckpoint::CheckpointReader *' at 0x7fdd46deef60> >, tensor_str='_CHECKPOINTABLE_OBJECT_GRAPH')
    369         return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str),
--> 370                                           status)
        status = <Swig Object of type 'TF_Status *' at 0x7fdd46deee40>
    371 

~/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self=<tensorflow.python.framework.errors_impl.raise_exception_on_not_ok_status object>, type_arg=None, value_arg=None, traceback_arg=None)
    527             compat.as_text(c_api.TF_Message(self.status.status)),
--> 528             c_api.TF_GetCode(self.status.status))
        global c_api.TF_GetCode = <built-in function TF_GetCode>
        self.status.status = undefined
    529     # Delete the underlying status object from memory otherwise it stays alive

NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
~/napari-bb-annotations/napari_bb_annotations/gui.py in <lambda>()
     29 
     30     run_lumi_btn = QPushButton("Tensorflow Predict on CURRENT image")
---> 31     run_lumi_btn.clicked.connect(lambda: run_lumi_on_image(viewer))
        global run_lumi_btn.clicked.connect = undefined
        global run_lumi_on_image = <function run_lumi_on_image at 0x7fde9dde8620>
        global viewer = undefined
     32     run_lumi_btn.setToolTip("Overwrites other predictions, Per 1 image with 20 bbs takes 20 seconds depending on CPU/GPU")
     33 

~/napari-bb-annotations/napari_bb_annotations/_key_bindings.py in run_lumi_on_image(viewer=Viewer(axes=Axes(visible=False, labels=True, col...ouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}))
    632             max_detections, only_class,
    633             ignore_class, debug, xlsx_spacing,
--> 634             classes_json, pixel_distance, new_labels)
        classes_json = None
        pixel_distance = 0
        new_labels = None
    635         if os.path.exists(csv_path_per_image):
    636             frames = [df, pd.read_csv(csv_path_per_image, index_col=False)]

~/miniconda3/envs/bbsulc/lib/python3.7/site-packages/luminoth/predict.py in predict_function(path_or_dir='/Users/pranathi.vemuri/Desktop/example_data/thin_flow_cell_8apr2021.avi kept stack0002.tif', config_files=None, checkpoint='1a0f3002f674', override_params=None, output_path='/Users/pranathi.vemuri/Desktop/example_data/bb_l...hin_flow_cell_8apr2021.avi kept stack0002.tif.csv', save_media_to=None, min_prob=0.5, max_prob=1.0, max_detections=100, only_class=None, ignore_class=None, debug=False, xlsx_spacing=2, classes_json=None, pixel_distance=0, new_labels=None)
    435 
    436     # Instantiate the model indicated by the config.
--> 437     network = PredictorNetwork(config)
        network = undefined
        global PredictorNetwork = <class 'luminoth.utils.predicting.PredictorNetwork'>
        config = {'train': {'debug': True, 'seed': None, 'batch_size': 1, 'job_dir': '/Users/pranathi.vemuri/.luminoth/checkpoints', 'ignore_scope': None, 'tf_debug': False, 'run_name': '1a0f3002f674', 'no_log': False, 'display_every_steps': None, 'display_every_secs': 300, 'random_shuffle': True, 'save_timeline': False, 'save_checkpoint_secs': 600, 'checkpoints_max_keep': 1, 'save_summaries_steps': None, 'save_summaries_secs': 30, 'full_trace': False, 'clip_by_norm': False, 'learning_rate': {'decay_method': 'piecewise_constant', 'boundaries': [90000, 160000, 250000], 'values': [0.0003, 0.0001, '3e-05', '1e-05']}, 'optimizer': {'type': 'momentum', 'momentum': 0.9}, 'num_epochs': 1000, 'image_vis': 'train', 'var_vis': None}, 'eval': {'image_vis': 'eval'}, 'dataset': {'type': 'object_detection', 'dir': '/Users/pranathi.vemuri/.luminoth/checkpoints/1a0f3002f674', 'split': 'train', 'image_preprocessing': {'min_size': 600, 'max_size': 1024}, 'data_augmentation': None}, 'model': {'type': 'fasterrcnn', 'network': {'num_classes': 4, 'with_rcnn': True}, 'batch_norm': False, 'base_network': {'architecture': 'resnet_v1_101', 'trainable': True, 'weights': None, 'download': True, 'endpoint': None, 'fine_tune_from': 'block2', 'train_batch_norm': False, 'use_tail': True, 'freeze_tail': False, 'output_stride': 16, 'arg_scope': {'weight_decay': 0.0005}}, 'loss': {'rpn_cls_loss_weight': 1.0, 'rpn_reg_loss_weights': 1.0, 'rcnn_cls_loss_weight': 1.0, 'rcnn_reg_loss_weights': 1.0}, 'anchors': {'base_size': 64, 'scales': [0.25, 0.5, 1, 2], 'ratios': [0.5, 1, 2], 'stride': 16}, 'rpn': {'activation_function': 'relu6', 'l2_regularization_scale': 0.0005, 'l1_sigma': 3.0, 'loss': {'type': 'cross_entropy'}, 'num_channels': 512, 'kernel_shape': [3, 3], 'rpn_initializer': {'type': 'random_normal_initializer', 'mean': 0.0, 'stddev': 0.01}, 'cls_initializer': {'type': 'random_normal_initializer', 'mean': 0.0, 'stddev': 0.01}, 'bbox_initializer': {'type': 'random_normal_initializer', 'mean': 0.0, 'stddev': 0.001}, 'proposals': {'pre_nms_top_n': 12000, 'post_nms_top_n': 2000, 'apply_nms': True, 'nms_threshold': 0.7, 'min_size': 0, 'clip_after_nms': False, 'filter_outside_anchors': False, 'min_prob_threshold': 0.0}, 'target': {'allowed_border': 0, 'clobber_positives': False, 'foreground_threshold': 0.7, 'background_threshold_high': 0.3, 'background_threshold_low': 0.0, 'foreground_fraction': 0.5, 'minibatch_size': 256, 'random_seed': None}}, 'rcnn': {'layer_sizes': [], 'dropout_keep_prob': 1.0, 'activation_function': 'relu6', 'l2_regularization_scale': 0.0005, 'l1_sigma': 1.0, 'loss': {'type': 'cross_entropy'}, 'use_mean': True, 'target_normalization_variances': [0.1, 0.2], 'rcnn_initializer': {'type': 'variance_scaling_initializer', 'factor': 1.0, 'uniform': True, 'mode': 'FAN_AVG'}, 'cls_initializer': {'type': 'random_normal_initializer', 'mean': 0.0, 'stddev': 0.01}, 'bbox_initializer': {'type': 'random_normal_initializer', 'mean': 0.0, 'stddev': 0.001}, 'roi': {'pooling_mode': 'crop', 'pooled_width': 7, 'pooled_height': 7, 'padding': 'VALID'}, 'proposals': {'class_max_detections': 2000, 'class_nms_threshold': 0.5, 'total_max_detections': 100, 'min_prob_threshold': 0.5}, 'target': {'foreground_fraction': 0.25, 'minibatch_size': 256, 'foreground_threshold': 0.5, 'background_threshold_high': 0.5, 'background_threshold_low': 0.0}}}}
    438     # Iterate over files and run the model on each.
    439     df = pd.DataFrame(columns=LUMI_CSV_COLUMNS)

~/miniconda3/envs/bbsulc/lib/python3.7/site-packages/luminoth/utils/predicting.py in __init__(self=<luminoth.utils.predicting.PredictorNetwork object>, config={'train': {'debug': True, 'seed': None, 'batch_s...d_high': 0.5, 'background_threshold_low': 0.0}}}})
     60                 ckpt = ckpt.all_model_checkpoint_paths[-1]
     61                 saver = tf.train.Saver(sharded=True, allow_empty=True)
---> 62                 saver.restore(self.session, ckpt)
        saver.restore = <bound method Saver.restore of <tensorflow.python.training.saver.Saver object at 0x7fdea34eea90>>
        self.session = <tensorflow.python.client.session.Session object at 0x7fdd455272b0>
        ckpt = '/Users/pranathi.vemuri/.luminoth/checkpoints/1a0f3002f674/model.ckpt-837929'
     63                 tf.logging.info('Loaded checkpoint.')
     64             else:

~/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py in restore(self=<tensorflow.python.training.saver.Saver object>, sess=<tensorflow.python.client.session.Session object>, save_path='/Users/pranathi.vemuri/.luminoth/checkpoints/1a0f3002f674/model.ckpt-837929')
   1290         # a helpful message (b/110263146)
   1291         raise _wrap_restore_error_with_msg(
-> 1292             err, "a Variable name or other graph key that is missing")
        err = undefined
   1293 
   1294       # This is an object-based checkpoint. We'll print a warning and then do

NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key fasterrcnn_1/rcnn/fc_bbox/b not found in checkpoint
	 [[node save/RestoreV2 (defined at /Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/luminoth/utils/predicting.py:61) ]]

Caused by op 'save/RestoreV2', defined at:
  File "./napari_bb_annotations/launcher/bb_annotations.py", line 17, in <module>
    main()
  File "./napari_bb_annotations/launcher/bb_annotations.py", line 13, in main
    launch_viewer()
  File "./napari_bb_annotations/launcher/bb_annotations.py", line 9, in launch_viewer
    connect_to_viewer(viewer)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/napari/_qt/qt_event_loop.py", line 253, in gui_qt
    run(force=force, gui_exceptions=gui_exceptions, _func_name='gui_qt')
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/napari/_qt/qt_event_loop.py", line 347, in run
    app.exec_()
  File "/Users/pranathi.vemuri/napari-bb-annotations/napari_bb_annotations/gui.py", line 31, in <lambda>
    run_lumi_btn.clicked.connect(lambda: run_lumi_on_image(viewer))
  File "/Users/pranathi.vemuri/napari-bb-annotations/napari_bb_annotations/_key_bindings.py", line 634, in run_lumi_on_image
    classes_json, pixel_distance, new_labels)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/luminoth/predict.py", line 437, in predict_function
    network = PredictorNetwork(config)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/luminoth/utils/predicting.py", line 61, in __init__
    saver = tf.train.Saver(sharded=True, allow_empty=True)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 832, in __init__
    self.build()
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 844, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 881, in _build
    build_save=build_save, build_restore=build_restore)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 507, in _build_internal
    restore_sequentially, reshape)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 385, in _AddShardedRestoreOps
    name="restore_shard"))
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 332, in _AddRestoreOps
    restore_sequentially)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/training/saver.py", line 580, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1572, in restore_v2
    name=name)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key fasterrcnn_1/rcnn/fc_bbox/b not found in checkpoint
	 [[node save/RestoreV2 (defined at /Users/pranathi.vemuri/miniconda3/envs/bbsulc/lib/python3.7/site-packages/luminoth/utils/predicting.py:61) ]]

2021-04-13:17:47:07,30 INFO     [_key_bindings.py:577] Pressed button to run luminoth prediction
Notification
Found 1 files to predict.
2021-04-13 17:47:14.942622: ```

**Comment by pranathivemuri** [comment]
Addressed by loading network once and lru cache
